name: Build and deploy Search Engine to Azure Web App

on:
  push:
    branches: [ main ]
    paths:
      - 'Project/Search Engine/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'microsoft'
          java-version: '21'

      - name: Build with Maven
        working-directory: 'Project/Search Engine'
        run: mvn -B clean package       # produces target/…jar

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: 'Project/Search Engine/target/*-shaded.jar'

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: Production
      url: ${{ steps.deploy.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: java-app
          path: 'Project/Search Engine/target/*-shaded.jar'

      - name: Azure login
        uses: azure/login@v2
        with:
          client-id:       ${{ secrets.AZUREAPPSERVICE_CLIENTID_E43126B1553641C39BE6F000638BBF27 }}
          tenant-id:       ${{ secrets.AZUREAPPSERVICE_TENANTID_5F5132C308E14735AAA477250B11CB5E }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_8FB76D3F89CA46A18A0C018722F4A2FB }}

      - name: Deploy to Azure Web App
        id: deploy
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'searchengine'
          slot-name: 'Production'
          package: '*-shaded.jar'
